# Generated by Django 3.2.9 on 2022-03-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0002_auto_20220314_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='calificacion_minim',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
